// Single source of truth for the mascot's mood→art maps.
//
// TWO LAYERS:
//   ANIM_ASSETS     — mood → static first-frame PNG. Always present; this is
//                     the Reduce Motion path, the flipbook's first-decode
//                     underlay, and the fallback for any mood without a strip.
//   FLIPBOOK_ASSETS — mood → sprite-strip flipbook (SenpaiFlipbook plays it).
//                     Missing key ⇒ the mascot renders the static PNG.
//
// WHY THE STRIPS ARE *STATIC* WebP: animated WebP/APNG via expo-image produced
// black-box / pixelated rendering on Apple-silicon iOS simulators (a DECODER
// bug — it persisted even after scripts/fix-senpai-webp.sh cured the file-level
// bugs), so animated formats were deliberately dropped. Each strip here is a
// single static lossy WebP with alpha (24 frames × 280px laid out horizontally,
// 6720×280), stepped by translateX at 12fps — a completely different decode
// path that sidesteps the animated decoder entirely. Strips are generated by
// scripts/build-senpai-flipbooks.sh from zenki_senpai_animations/transparent/.
//
// ASSET-VERSIONING TWIN RULE (prior incident: stale caches ghosted old frames):
//   Any regeneration that changes bytes under src/assets/senpai/** ⇒
//     1. bump ASSET_VER in scripts/build-senpai-flipbooks.sh (v1 → v2) AND
//        every `_vN` filename require()'d below (new filename ⇒ new Metro
//        asset hash ⇒ cold cache in every layer, immune by construction), AND
//     2. bump the `@senpai_asset_cache_v` VERSION constant in SenpaiMascot.tsx
//        (one-shot expo-image cache clear — belt and braces).
//
// Lives in its own module (rather than SenpaiMascot) so SenpaiFlipbook and the
// mascot can both import it without a circular dependency.

export const ANIM_ASSETS: Record<string, any> = {
  idle: require('../assets/senpai/senpai_idle.png'),
  cheering: require('../assets/senpai/senpai_cheering.png'),
  impressed: require('../assets/senpai/senpai_impressed.png'),
  encouraging: require('../assets/senpai/senpai_encouraging.png'),
  celebrating: require('../assets/senpai/senpai_celebrating.png'),
  sleeping: require('../assets/senpai/senpai_sleep.png'),
  disappointed: require('../assets/senpai/senpai_cry.png'),
  // Non-mood art keys (not part of MascotMood — the mascot selects these
  // directly): 'think' while a reply is in flight (D7), 'wave' for the
  // wake-up arc greet beat (H5).
  think: require('../assets/senpai/senpai_think.png'),
  wave: require('../assets/senpai/senpai_wave.png'),
};

export interface FlipbookEntry {
  /** require()'d STATIC WebP strip, frames laid out horizontally. */
  strip: any;
  /** Frame count in the strip (all current strips: 24). */
  frames: number;
  /** Playback rate (all current strips: 12). */
  fps: number;
}

// Mood → animated strip. Missing key ⇒ mascot falls back to the static PNG.
// Runtime keys mirror ANIM_ASSETS (sleeping→senpai_sleep, disappointed→
// senpai_cry are the source-clip renames).
export const FLIPBOOK_ASSETS: Partial<Record<string, FlipbookEntry>> = {
  idle:         { strip: require('../assets/senpai/flipbook/senpai_idle_strip_v1.webp'),        frames: 24, fps: 12 },
  cheering:     { strip: require('../assets/senpai/flipbook/senpai_cheering_strip_v1.webp'),    frames: 24, fps: 12 },
  impressed:    { strip: require('../assets/senpai/flipbook/senpai_impressed_strip_v1.webp'),   frames: 24, fps: 12 },
  encouraging:  { strip: require('../assets/senpai/flipbook/senpai_encouraging_strip_v1.webp'), frames: 24, fps: 12 },
  celebrating:  { strip: require('../assets/senpai/flipbook/senpai_celebrating_strip_v1.webp'), frames: 24, fps: 12 },
  sleeping:     { strip: require('../assets/senpai/flipbook/senpai_sleep_strip_v1.webp'),       frames: 24, fps: 12 },
  disappointed: { strip: require('../assets/senpai/flipbook/senpai_cry_strip_v1.webp'),         frames: 24, fps: 12 },
  think:        { strip: require('../assets/senpai/flipbook/senpai_think_strip_v1.webp'),       frames: 24, fps: 12 },
  wave:         { strip: require('../assets/senpai/flipbook/senpai_wave_strip_v1.webp'),        frames: 24, fps: 12 },
};
